[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery = "Cir3otRBVbM5UPikSJM5mGrFP44hWyvuG1cr7dzQggvW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
